# C++错误处理到底在处理什么?

## Invariant

Invariant是什么呢? 一个对象应该满足的一致性约束, 即为此对象的invariant. 比如说, 我们实现一个基于红黑树的```map```类, 有两个成员:

```cpp
class map
{
    size_t _size;
    node_t _root;
};
```

它的invariant即为, 以```_root```为根节点的索引数的```node```数量应该与```_size```相等. 

对于一个对象的invariant, 我们需要了解以下几点:

+ 对象构造完成后, invariant一定成立
+ 一个对象的方法执行前, 对象的invariant一定成立
+ 一个对象的方法执行后, 对象的invariant一定成立
+ 一个对象的方法执行中, 对象的invariant可能暂时违反

```cpp
void vector::push_back(const T& t)
{
    // a. invariant holds
    _paylod[_size] = t;
    // b. invariant breaks
    ++_size;
    // c. invariant holds
}
```

如果对象的invariant暂时被破坏时, 此时出现了一个error, 对象的invariant会怎样? 这直接关系到程序的正确性.

## Exception safety
Exception safety用于描述, 当一个对象的方法执行期间, 如果出错, 这个对象的invariant会怎样.

+ no guarantee: 对象的invariant不再成立, 或者存在资源泄露, 可能会出现任何情况
+ basic guarantee: 对象的invariant成立, 但我们不知道它具体的状态是什么, 此时, 这个对象不能再被使用, 只能reset成原始状态, 或者销毁
+ strong guarantee: 对象的invariant成立, 且状态与调用方法之前完全相同, 即这个失败的操作, 没有对这个对象产生任何效果
+ no excpet: 此操作保证一定成功, 保证不会抛出任何异常

对于错误处理来说, 我们究竟要处理什么?

1. 保证对象的方法执行出现错误后, 对象的invariant仍然成立
2. 无任何资源泄露
3. 向上层报这个错误

basic guarantee/strong guarantee都是第一、第二点的体现, 只不过程度上有所不同. 对于第三点, 我们直接throw一个异常, 或者```return```一个```error code```就可以了

## Execution Root

异常处理的第一个目的是让我们的程序的invariant可以恢复, 遮掩它可以安全地忽略这个异常, 继续执行. 但是这个异常不能发生过就完了, 我们需要报告此异常, 无论是返回给客户终端还是记录一条log. 即异常处理的第三个目的: 上报异常.

我们在什么地方catch呢? 答案是: Execution Root.

+ main: 如果不处理, 一直向上传, 最终会terminate整个程序
+ 线程的主函数: 如果不处理, 一直向上传, 最终会terminate整个程序
+ 处理用户请求的根函数

错误处理的实质是: 我们在出错时, 进行一些处理, 保证:

+ 对象invariant不被破坏
+ 无资源泄露(RAII)
+ 错误上报或者记录log